# Generated by Django 4.0.4 on 2022-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_remove_agent_properties_cards_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='image',
            field=models.ImageField(default='default.png', upload_to='cards_pics'),
        ),
    ]
