# Generated by Django 4.0.4 on 2022-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_cards_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(default='default.png', upload_to='agent_pics'),
        ),
    ]
