# Generated by Django 4.0.6 on 2022-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='residence',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
